### PR TITLE
Fix vcf creation scripts to remove whitespace from sample names when …

### PR DESCRIPTION
**Pull request by tfenne**
…writing them to the INFO field as whitespace is not allowed in the INFO field of a VCF.  The sample name in the #CHROM line is unchanged as whitespace is allowed there.

### CODE REVIEW

**Comment by tfenne** [comment]
Hopefully this PR can be accepted - it's a small change that should only affect users who are creating VCFs with VarDict _and_ have provided sample names that contain whitespace.  The VCF spec prohibits whitespace in the `INFO` field of the variant lines, and I've run into an issue where pipelines are being run on samples with spaces in the names; VarDict runs fine, but the downstream code which reads the VCF is failing due to the spaces in the INFO field.

**Comment by mjafin** [comment]
Thanks @tfenne 

Ping @zhongwulai @chapmanb I've accepted this pull request as-is.

**Comment by tfenne** [comment]
Thanks @mjafin !

**Comment by chapmanb** [comment]
Tim and Miika -- thanks much for this, I updated the conda package for VarDict as well.

**Pull request merged**
